### ISSUE TITLE
Redundant in Mac

### ISSUE THREAD

**Issue by bean5** [MCluck90/atom-change-tabs#1]
May be a good idea to mention in the description that in Mac, this is redundant. In Mac, the Mac + 1 or Mac + 2, etc. do the same thing.

**Comment by mikecluck** [comment]
Good to know. Maybe I'll add a note to the README about this.

**Comment by bean5** [comment]
Wow, fast response time. Kudos man.

**Comment by mikecluck** [comment]
Haha, thanks. The benefits of downtime at work and email notifications.
